### ISSUE TITLE
Get-EasitGOItem can't handle duplicate of field names.

### ISSUE THREAD

**Issue by plingy** [easitab/Easit.GO.Webservice#97]
Get-EasitGOItem can't handle duplicate of field names.

**Comment by easitab-owner** [comment]
Get-EasitGOItem does handle columns / fields with the same name. 'Get-GOItems' in the module 'EasitGoWebservice' does not.
If the view in Easit GO contains multiple fields with the same name 'Get-EasitGOItem' will create a list with all the values and rawValues and add it as the value for the field name.

Each field / column from the view can be accessed separately via the 'PropertyObjects' property.

**Comment by easitanth** [comment]
Get-EasitGOItem does handle columns / fields with the same name. 'Get-GOItems' in the module 'EasitGoWebservice' does not.
If the view in Easit GO contains multiple fields with the same name 'Get-EasitGOItem' will create a list with all the values and rawValues and add it as the value for the field name.

Each field / column from the view can be accessed separately via the 'PropertyObjects' property
